services:
  cats-dogs-classifier:
    image: "${DOCKER_USERNAME}/cats-dogs-classifier:latest"
    container_name: cats-dogs-classifier

    ports:
      - "8000:8000"

    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8000
      LOG_LEVEL: INFO

    volumes:
      - ../models:/app/models:ro

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 20s
